site_name: blendOS Docs
site_url: https://blend-docs-material.pages.dev
site_author: "blendOS Contributors"
site_description: "A seamless, yet robust experience. These are the blendOS docs."
repo_url: https://git.blendos.co/asterisk/blend-docs-material
repo_name: Asterisk/blend-docs-material
edit_uri: edit/main/docs
theme:
  font: false
  name: material
  custom_dir: overrides
  logo: assets/img/logo.png
  favicon: assets/img/logo.png
  icon:
    repo: fontawesome/brands/git-alt
    edit: material/pencil
    view: material/eye
    admonition:
      tip: fontawesome/solid/lightbulb
      danger: material/lightning-bolt
      question: fontawesome/solid/question
      bug: material/bug
      info: fontawesome/solid/info
      abstract: material/clipboard-text-multiple
      warning: fontawesome/solid/exclamation
      note: material/pencil
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.prune
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - content.tabs.link
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    - content.action.edit
    - content.action.view
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

copyright: "&copy; 2024 blendOS contributors. All content under <a href='https://creativecommons.org/licenses/by-sa/4.0/' target='_blank' rel='noopener noreferrer'>CC BY-SA 4.0 International</a>."
watch:
  - "includes"
  - "overrides"
  - "main.py"
extra:
  generator: false
  analytics:
    provider: custom
  social:
    - icon: fontawesome/solid/earth-americas
      link: https://blendos.co
      name: blendOS Website
    - icon: simple/x
      link: https://x.com/@blend_os
      name: blendOS X Feed
    - icon: fontawesome/brands/discord
      link: https://discord.gg/fvMpV8ZNxD
      name: blendOS Discord
    - icon: fontawesome/brands/telegram
      link: https://t.me/blendos
      name: blendOS Telegram
    - icon: simple/matrix
      link: https://matrix.to/#/#blendos:matrix.org
      name: blendOS Matrix Room
    - icon: simple/uptimekuma
      link: https://status.asterisk.lol/status/blendos
      name: blendOS Status
    - icon: fontawesome/brands/github
      link: https://github.com/blend_os
      name: blendOS Github
    - icon: fontawesome/brands/gitlab
      link: https://git.blendos.co/blendos
      name: blendOS Gitlab Server

markdown_extensions:
  - abbr
  - admonition
  - pm_attr_list
  # - pm_markdown_captions
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
  - toc:
      anchorlink: false
      permalink: "#"
      permalink_title: ""
  - tables
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets:
      check_paths: true
      url_download: true
      url_max_size: 33554432
      url_timeout: 10
      auto_append:
        - includes/abbreviations.md
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.magiclink:
      custom: 
        blendgit:
          host: https://git.blendos.co
          label: "BlendOS Gitlab"
          type: gitlab
          www: false
      hide_protocol: true
      normalize_issue_symbols: false
      repo_url_shorthand: true
      repo_url_shortener: true
      provider: github
      user: blend-os
      repo: blendos
      social_url_shorthand: true
      social_url_shortener: true
  - pymdownx.keys
  - pymdownx.smartsymbols:
      trademark: true
      copyright: true
      registered: true
      care_of: true
      plusminus: true
      arrows: true
      notequal: true
      fractions: true
      ordinal_numbers: true
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.inlinehilite



plugins:
  - search
  - glightbox
  - macros
  - redirects:
      redirect_maps: 
        'docs/intro.md': 'index.md'
        'docs/index.md': 'index.md'
        'docs/utilities/bpkg.md': 'reference/utils/bpkg.md'
        'docs/faq.md': 'faq.md'
        'docs/category/installation.md': 'install/README.md'
        'docs/installation/normal-pc.md': 'install/normal-pc.md'
        'docs/installation/mac-t2.md': 'install/t2.md'
        'docs/installation/container.md': 'install/post-install/container-guide.md'
        'contribution.md': 'contributing.md'

  - group:
      enabled: !ENV CI 
      plugins:
        - privacy:
            enabled: !ENV [OFFLINE, false]
            cache: true
            cache_dir: .cache/plugins/privacy
            log: true
            assets: true
            assets_fetch: true
            assets_fetch_dir: assets/external
            links: true
            links_noopener: true
        - offline:
            enabled: !ENV [OFFLINE, false]
        - social:
            enabled: true
            cache_dir: .cache/plugins/social
            cards: true
            cards_dir: assets/images/social
            cards_layout_options:
              font_family: Archivo
              background_color: "#1e2029"
              color: "#21af90"
        - git-authors:
            show_email_address: false
            show_contribution: true
        - git-revision-date-localized:
            type: timeago 
            



extra_css:
  - assets/css/extra.css

extra_javascript:
  - assets/js/tablesort.min.js
  - assets/js/sorter.js

nav:
  - Home:
    - Home: index.md
    - FAQ: faq.md
    - Offline Reading: offline.md
    - Contributing: contributing.md
  - Download: 
    - Download: download/README.md
  - Installation:
     - Installation: install/README.md
     - Normal PC: install/normal-pc.md
     - T2 Mac: install/t2.md
     - Post-Installation:
       - Post-Installation: install/post-install/README.md
       - Container Management: install/post-install/container-guide.md
       - System Customization: install/post-install/system-customization.md
  - Reference:
      - Reference: reference/README.md
      - Container List: reference/container-list.md
      - ISO Building: reference/iso-building.md
      - Utilities: 
        - Utilities: reference/utils/README.md
        - akshara: reference/utils/akshara.md
        - bpkg: reference/utils/bpkg.md
        - blend-inst: reference/utils/blend-inst.md
      - Files:
        - Files: reference/configs/README.md
        - system.yaml: reference/configs/system.md
